const JUDETE = {
    AB: 'ALBA',
    AR: 'ARAD',
    AG: 'ARGES',
    BC: 'BACAU',
    BH: 'BIHOR',
    BN: 'BISTRITA NASAUD',
    BT: 'BOTOSANI',
    BR: 'BRAILA',
    BV: 'BRASOV',
    'Municipiul București': 'BUCURESTI',
    BZ: 'BUZAU',
    CL: 'CALARASI',
    CS: 'CARAS SEVERIN',
    CJ: 'CLUJ',
    CT: 'CONSTANTA',
    CV: 'COVASNA',
    DB: 'DIMBOVITA',
    DJ: 'DOLJ',
    GL: 'GALATI',
    GR: 'GIURGIU',
    GJ: 'GORJ',
    HR: 'HARGHITA',
    HD: 'HUNEDOARA',
    IL: 'IALOMITA',
    IS: 'IASI',
    IF: 'ILFOV',
    MM: 'MARAMURES',
    MH: 'MEHEDINTI',
    MS: 'MURES',
    NT: 'NEAMT',
    OT: 'OLT',
    PH: 'PRAHOVA',
    SJ: 'SALAJ',
    SM: 'SATU MARE',
    SB: 'SIBIU',
    SV: 'SUCEAVA',
    TR: 'TELEORMAN',
    TM: 'TIMIS',
    TL: 'TULCEA',
    VL: 'VILCEA',
    VS: 'VASLUI',
    VN: 'VRANCEA'
}
const List_judete = [
    'ALBA', 'ARAD', 'ARGES', 'BACAU', 'BIHOR', 'BISTRITA NASAUD', 'BOTOSANI', 'BRAILA', 'BRASOV', 'BUCURESTI', 'BUZAU',
    'CALARASI', 'CARAS SEVERIN', 'CLUJ', 'CONSTANTA', 'COVASNA', 'DIMBOVITA', 'DOLJ', 'GALATI', 'GIURGIU', 'GORJ',
    'HARGHITA', 'HUNEDOARA', 'IALOMITA', 'IASI', 'ILFOV', 'MARAMURES', 'MEHEDINTI', 'MURES', 'NEAMT', 'OLT', 'PRAHOVA',
    'SALAJ', 'SATU MARE', 'SIBIU', 'SUCEAVA', 'TELEORMAN', 'TIMIS', 'TULCEA', 'VILCEA', 'VASLUI', 'VRANCEA'
];

export { JUDETE , List_judete };
